# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
# Step 1: Echo a basic message (optional)
- script: echo "Starting build pipeline..."
  displayName: 'Run a one-line script'

# Step 2: Copy files to the artifact staging directory
- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)'  # Copy from repository source
    Contents: '**'  # Copy all files (HTML, CSS, JS, etc.)
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

# Step 3: Archive files into a ZIP package
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Build.ArtifactStagingDirectory)'  
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/drop.zip'
    replaceExistingArchive: true

# Step 4: Publish the ZIP file as an artifact
- task: PublishBuildArtifacts@1
  inputs:
    PathToPublish: '$(Build.ArtifactStagingDirectory)/drop.zip'  
    ArtifactName: 'drop'
    publishLocation: 'Container'
